{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 18, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 5 in scenario \"Call /QuestionnaireResponse with invalid FHIR QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_invalid_fhir_questionnaireresponse", "rerun": "0"}, "1": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 23 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_content[9730675929-DELETE-405]", "rerun": "0"}, "2": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 23 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_content[9730675929-OPTIONS-405]", "rerun": "0"}, "3": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 23 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_content[9730675929-PATCH-405]", "rerun": "0"}, "4": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 23 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_content[9730675929-GET-405]", "rerun": "0"}, "5": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 23 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_content[9730675929-PUT-405]", "rerun": "0"}, "6": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 153 in scenario \"Call /QuestionnaireResponse with HTTP verbs returning no content\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_http_verbs_returning_no_content[HEAD-405]", "rerun": "0"}, "7": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 274 in scenario \"Check invalid URL returns a 404 for QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_check_invalid_url_returns_a_404_for_questionnaireresponse[%2FQuestionnaireResponse]", "rerun": "0"}, "8": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 274 in scenario \"Check invalid URL returns a 404 for QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_check_invalid_url_returns_a_404_for_questionnaireresponse[%2FFHIR%2FR3%2FQuestionnaireResponse]", "rerun": "0"}, "9": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 274 in scenario \"Check invalid URL returns a 404 for QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_check_invalid_url_returns_a_404_for_questionnaireresponse[%2Ffhir%2Fr4%2FQuestionnaireResponse]", "rerun": "0"}, "10": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 274 in scenario \"Check invalid URL returns a 404 for QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_check_invalid_url_returns_a_404_for_questionnaireresponse[%2FFHIR%2FR4%2FQUESTIONNAIRERESPONSE]", "rerun": "0"}, "11": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 274 in scenario \"Check invalid URL returns a 404 for QuestionnaireResponse\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_check_invalid_url_returns_a_404_for_questionnaireresponse[%2FFHIR%2FR4%2Fquestionnaireresponse]", "rerun": "0"}, "12": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 405 in scenario \"Call /QuestionnaireResponse with incorrect Content-Type\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_incorrect_contenttype[application%2Fjson]", "rerun": "0"}, "13": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 405 in scenario \"Call /QuestionnaireResponse with incorrect Content-Type\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_incorrect_contenttype[application%2Ffhir]", "rerun": "0"}, "14": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 405 in scenario \"Call /QuestionnaireResponse with incorrect Content-Type\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_incorrect_contenttype[application%2Fxml]", "rerun": "0"}, "15": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 405 in scenario \"Call /QuestionnaireResponse with incorrect Content-Type\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_incorrect_contenttype[application%2Ffhir%2Bjson%3B%20charset%3DWindows-1252]", "rerun": "0"}, "16": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"A questionnaire response:\". Line 405 in scenario \"Call /QuestionnaireResponse with incorrect Content-Type\" in the feature \"/Users/richa.jha/Desktop/NHS_Proxy/proxy-validated-relationships-service/tests/test_api/features/QuestionnaireResponse/2_operation_outcomes.feature\"\n", "test_name": "test_call_questionnaireresponse_with_incorrect_contenttype[empty value]", "rerun": "0"}, "17": {"status": "FAIL", "message": "   ValueError: Missing required config. You must pass cli option --apigee-access-token or environment variable APIGEE_ACCESS_TOKEN.\n", "test_name": "test_test_malformed_json_request_body", "rerun": "0"}}, "suite_name": "test_api/test_step_definitions.py"}}}, "date": "July 15, 2024", "start_time": 1721059122.964761, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "18", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "18"}