{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   socket.gaierror: [Errno 8] nodename nor servname provided, or not known\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x10d61ed10>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk%22', port=443): Max retries exceeded with url: /FHIR/R4/Patient%22/%229730676399%22/%22no%20endpoint%22 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10d61ed10>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk%22', port=443): Max retries exceeded with url: /FHIR/R4/Patient%22/%229730676399%22/%22no%20endpoint%22 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10d61ed10>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "test_name": "test_when_no_pds_response_cache_available[%2FFHIR%2FR4%2FPatient-9730676399-no endpoint]", "rerun": "0"}, "1": {"status": "FAIL", "message": "   socket.gaierror: [Errno 8] nodename nor servname provided, or not known\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x10ed8e350>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk%22', port=443): Max retries exceeded with url: /FHIR/R4/Patient%22/%229730676399%22/%22RelatedPerson%22 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10ed8e350>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk%22', port=443): Max retries exceeded with url: /FHIR/R4/Patient%22/%229730676399%22/%22RelatedPerson%22 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x10ed8e350>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk%22' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "test_name": "test_when_no_pds_response_cache_available[%2FFHIR%2FR4%2FPatient-9730676399-RelatedPerson]", "rerun": "0"}}, "suite_name": "test_api/test_pds_cache.py"}}}, "date": "July 17, 2024", "start_time": 1721225238.666949, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}