{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   socket.gaierror: [Errno 8] nodename nor servname provided, or not known\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x11cb9add0>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk' ([Errno 8] nodename nor servname provided, or not known)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk', port=443): Max retries exceeded with url: /FHIR/R4/Patient/9730676399 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x11cb9add0>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk' ([Errno 8] nodename nor servname provided, or not known)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mock.validated-relationships-service-dev.national.nhs.uk', port=443): Max retries exceeded with url: /FHIR/R4/Patient/9730676399 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x11cb9add0>: Failed to resolve 'mock.validated-relationships-service-dev.national.nhs.uk' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "test_name": "test_when_response_from_pds_is_null_it_shouldnt_be_added_to_cache", "rerun": "0"}}, "suite_name": "test_api/test_pds_cache.py"}}}, "date": "July 17, 2024", "start_time": 1721204872.457839, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}